apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.name }}
  description: ${{ parameters.description }}
spec:
  type: service
  lifecycle: production
  owner: ${{ parameters.owner }}
